version: 2
jobs:
  build:
    working_directory: ~/demo-app
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - demo-app-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: demo-app-maven-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/demo-app/src/webapp/node_modules
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/demo-app
    environment:
      - MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml"}}
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git public_access:master
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: public_access